# generate示例配置
logging:
  level: info
streams:
  - input:
      type: "generate"
      context: '{ "timestamp": 1625000000000, "value": 10, "sensor": "temp_1" }'
      interval: 1ms
      batch_size: 1000

    buffer:
      type: "memory"
      capacity: 10
      timeout: 10s
    pipeline:
      thread_num: 4
      processors:
#        - type: "batch"
#          count: 3
#          timeout_ms: 10000
#          data_type: "binary"
        - type: "json_to_arrow"

        - type: "sql"
          # SQL查询语句，支持标准SQL语法
          query: "SELECT sum(value),avg(value) ,111 as x FROM flow  group by sensor"
#        - type: "arrow_to_json"


    output:
      type: "stdout"
